# Generated by Django 5.2.8 on 2025-11-06 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFormCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_url', models.URLField(max_length=1000, unique=True)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('form_path', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'application_form_cache',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=255, unique=True)),
                ('collection', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('agency', models.CharField(blank=True, max_length=500)),
                ('department', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('synopsis_url', models.URLField(blank=True, max_length=1000)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'opportunities',
                'indexes': [models.Index(fields=['collection'], name='opportuniti_collect_c1e552_idx'), models.Index(fields=['close_date'], name='opportuniti_close_d_92d7b4_idx'), models.Index(fields=['deadline'], name='opportuniti_deadlin_a61419_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('funding_types', models.JSONField(default=list)),
                ('interests_main', models.JSONField(default=list)),
                ('interests_sub', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AppliedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(max_length=255)),
                ('collection', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('agency', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('application_instructions', models.TextField(blank=True)),
                ('match_score', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('win_rate_reasoning', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applied_opportunities',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'opportunity_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(max_length=255)),
                ('collection', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('agency', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('match_score', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_opportunities',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'opportunity_id')},
            },
        ),
    ]
