# Generated by Django 5.2.8 on 2025-11-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(max_length=255, unique=True)),
                ('collection', models.CharField(help_text='Firebase collection name', max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('synopsis_url', models.URLField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('application_form_found', models.BooleanField(default=False)),
                ('application_form_url', models.URLField(blank=True, null=True)),
                ('application_instructions', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-close_date', '-deadline'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('funding_types', models.JSONField(default=list, help_text='List of funding types: Contracts, Grants, RFPs, Bids')),
                ('interests_main', models.JSONField(default=list, help_text='Main interest keywords')),
                ('interests_sub', models.JSONField(default=list, help_text='Sub interest keywords')),
                ('grants_by_interest', models.JSONField(default=list, help_text='Grants by interest')),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_opportunity_id', models.CharField(help_text='Original Firebase ID', max_length=255)),
                ('firebase_collection', models.CharField(max_length=100)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('application_instructions', models.TextField(blank=True)),
                ('match_score', models.FloatField(blank=True, help_text='Original matching score', null=True)),
                ('win_rate', models.FloatField(blank=True, help_text='Calculated win rate percentage', null=True)),
                ('win_rate_reasoning', models.TextField(blank=True, help_text='Explanation of win rate calculation')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_opportunities', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Applied Opportunities',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'firebase_opportunity_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_opportunity_id', models.CharField(max_length=255)),
                ('firebase_collection', models.CharField(max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Opportunities',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'firebase_opportunity_id')},
            },
        ),
    ]
